In [42]:
import pandas as pd

In [ ]:
# Importar as bases

# Base vendas
venda_df = pd.read_excel('base_teste_systock.xlsx', sheet_name='venda')

# Base pedido de compra
pedido_df = pd.read_excel('base_teste_systock.xlsx', sheet_name='pedido_compra')

# Base entrada de mercadoria
entrada_df = pd.read_excel('base_teste_systock.xlsx', sheet_name='entradas_mercadoria')

# Base produtos filial
filial_df = pd.read_excel('base_teste_systock.xlsx', sheet_name='produtos_filial')

# Base de fornecedor
fornecedor_df = pd.read_excel('base_teste_systock.xlsx', sheet_name='fornecedor')

# display(venda_df.info())
# display(venda_df)

# display(pedido_df.info())
# display(pedido_df)

# display(entrada_df.info())
# display(entrada_df)

# display(filial_df.info())
# display(filial_df)

# display(fornecedor_df.info())
# display(fornecedor_df)

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   venda_id        33 non-null     int64
 1   data_emissao    33 non-null     datetime64[us]
 2   horariomov      33 non-null     str
 3   produto_id      33 non-null     str
 4   qtde_vendida    33 non-null     float64
 5   valor_unitario  33 non-null     float64
 6   filial_id       33 non-null     int64
 7   item            33 non-null     int64
 8   unidade_medida  33 non-null     str
dtypes: datetime64[us](1), float64(2), int64(3), str(3)
memory usage: 2.4 KB

None

,venda_id,data_emissao,horariomov,produto_id,qtde_vendida,valor_unitario,filial_id,item,unidade_medida
0,1,2025-01-11,08:00:00,P1,5.00,78.93,1,1,UN
1,2,2025-03-02,08:00:00,P2,7.00,92.96,1,1,UN
2,3,2025-01-28,08:00:00,P3,9.00,197.61,1,1,UN
3,4,2025-01-10,08:00:00,P4,38.60,139.71,1,1,UN
4,5,2025-01-11,08:00:00,P5,3.00,126.79,1,1,UN
5,6,2025-01-24,08:00:00,P6,2.00,36.83,1,1,UN
6,7,2025-02-22,08:00:00,P7,5.00,40.75,1,1,UN
7,8,2025-01-26,08:00:00,P8,20.04,51.37,1,1,UN
8,9,2025-01-17,08:00:00,P9,6.00,172.55,1,1,UN
9,10,2025-01-03,08:00:00,P10,90.00,44.22,1,1,UN
10,11,2025-01-08,08:00:00,P11,6.00,190.37,1,1,UN
11,12,2025-01-21,08:00:00,P12,2.86,136.40,1,1,UN
12,13,2025-01-24,08:00:00,P13,13.00,61.85,1,1,UN
13,14,2025-02-07,08:00:00,P14,53.00,106.30,1,1,UN
14,15,2025-02-20,08:00:00,P15,27.00,43.40,1,1,UN
15,16,2025-02-17,08:00:00,P16,37.11,14.41,1,1,UN
16,17,2025-02-22,08:00:00,P17,3.00,139.80,1,1,UN
17,18,2025-02-18,08:00:00,P18,5.00,185.23,1,1,UN
18,19,2025-02-20,08:00:00,P19,10.00,182.51,1,1,UN
19,20,2025-02-28,08:00:00,P20,2.00,68.54,1,1,UN
20,21,2025-01-24,08:00:00,P21,25.00,61.85,1,1,UN
21,22,2025-02-07,08:00:00,P22,6.00,106.30,1,1,UN
22,23,2025-02-20,08:00:00,P23,7.00,43.40,1,1,UN
23,24,2025-02-17,08:00:00,P24,4.00,14.41,1,1,UN
24,25,2025-02-22,08:00:00,P25,8.00,139.80,1,1,UN
25,26,2025-02-18,08:00:00,P26,3.11,185.23,1,1,UN
26,27,2025-02-20,08:00:00,P27,3.00,182.51,2,1,UN
27,28,2025-03-28,08:00:00,P28,6.00,68.54,3,1,UN
28,29,2025-03-17,08:00:00,P24,5.00,14.41,1,1,UN
29,30,2025-03-22,08:00:00,P25,3.00,139.80,1,1,UN
30,31,2025-03-18,08:00:00,P26,4.00,185.23,1,1,UN
31,32,2025-03-20,08:00:00,P27,2.00,182.51,2,1,UN
32,33,2025-03-28,08:00:00,P28,1.00,68.54,3,1,UN

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pedido_id          29 non-null     int64
 1   data_pedido        29 non-null     datetime64[us]
 2   item               29 non-null     int64
 3   produto_id         29 non-null     str
 4   descricao_produto  29 non-null     str
 5   ordem_compra       29 non-null     int64
 6   qtde_pedida        29 non-null     int64
 7   filial_id          29 non-null     int64
 8   data_entrega       29 non-null     datetime64[us]
 9   qtde_entregue      29 non-null     int64
 10  preco_compra       29 non-null     float64
 11  fornecedor_id      29 non-null     int64
 12  Unnamed: 12        9 non-null      datetime64[us]
 13  Unnamed: 13        9 non-null      float64
 14  Unnamed: 14        9 non-null      str
 15  Unnamed: 15        9 non-null      str
 16  Unnamed: 16        9 non-null      float64
 17  Unnamed: 17        9 non-null      float64
 18  Unnamed: 18        9 non-null      float64
 19  Unnamed: 19        9 non-null      datetime64[us]
 20  Unnamed: 20        9 non-null      float64
 21  Unnamed: 21        9 non-null      float64
 22  Unnamed: 22        9 non-null      float64
dtypes: datetime64[us](4), float64(8), int64(7), str(4)
memory usage: 5.3 KB

None

,pedido_id,data_pedido,item,produto_id,descricao_produto,ordem_compra,qtde_pedida,filial_id,data_entrega,qtde_entregue,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,1,2025-01-02,1,P1,Produto 1,1,96,1,2025-02-27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,2,2025-01-07,1,P2,Produto 2,2,14,1,2025-01-07,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,3,2025-01-05,1,P3,Produto 3,3,12,1,2025-01-03,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,4,2025-01-22,1,P4,Produto 4,4,27,1,2025-01-28,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,5,2025-01-28,1,P5,Produto 5,5,35,1,2025-02-28,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5,6,2025-02-22,1,P6,Produto 6,6,98,1,2025-01-05,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
6,7,2025-03-01,1,P7,Produto 7,7,34,1,2025-02-01,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
7,8,2025-02-02,1,P8,Produto 8,8,29,1,2025-02-14,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
8,9,2025-01-15,1,P9,Produto 9,9,57,1,2025-01-28,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
9,10,2025-01-09,1,P10,Produto 10,10,49,1,2025-02-09,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
10,11,2025-02-22,1,P11,Produto 11,11,24,1,2025-01-08,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
11,12,2025-02-25,1,P12,Produto 12,12,91,1,2025-02-20,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
12,13,2025-02-23,1,P13,Produto 13,13,99,1,2025-02-02,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
13,14,2025-01-21,1,P14,Produto 14,14,96,1,2025-01-01,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
14,15,2025-02-04,1,P15,Produto 15,15,45,1,2025-01-04,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
15,16,2025-02-27,1,P16,Produto 16,16,84,1,2025-01-14,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
16,17,2025-01-08,1,P17,Produto 17,17,22,1,2025-01-19,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
17,18,2025-02-17,1,P18,Produto 18,18,63,1,2025-01-02,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
18,19,2025-02-19,1,P19,Produto 19,0,20,1,2025-01-08,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
19,20,2025-02-10,1,P20,Produto 20,0,25,1,2025-01-15,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
20,21,2025-02-25,1,P12,Produto 12,0,12,1,2025-02-20,0,...,1.0,P12,Produto 12,12.0,91.0,1.0,2025-02-20,48.0,43.0,6.92
21,22,2025-02-23,1,P13,Produto 13,0,4,1,2025-02-02,0,...,1.0,P13,Produto 13,13.0,99.0,1.0,2025-02-02,91.0,8.0,65.44
22,23,2025-01-21,1,P14,Produto 14,0,6,1,2025-01-01,0,...,1.0,P14,Produto 14,14.0,96.0,1.0,2025-01-01,27.0,69.0,21.91
23,24,2025-02-04,1,P15,Produto 15,0,8,1,2025-01-04,0,...,1.0,P15,Produto 15,15.0,45.0,1.0,2025-01-04,1.0,44.0,85.04
24,25,2025-02-27,1,P16,Produto 16,0,9,1,2025-01-14,0,...,1.0,P16,Produto 16,16.0,84.0,1.0,2025-01-14,51.0,33.0,64.17
25,26,2025-01-08,1,P17,Produto 17,0,4,1,2025-01-19,0,...,1.0,P17,Produto 17,17.0,22.0,1.0,2025-01-19,7.0,15.0,74.55
26,27,2025-02-17,1,P18,Produto 18,0,3,1,2025-01-02,0,...,1.0,P18,Produto 18,18.0,63.0,1.0,2025-01-02,17.0,46.0,24.94
27,28,2025-02-19,1,P19,Produto 19,0,3,1,2025-01-08,0,...,1.0,P19,Produto 19,19.0,40.0,1.0,2025-01-08,0.0,40.0,22.21
28,29,2025-02-10,1,P20,Produto 20,0,2,1,2025-01-15,0,...,1.0,P20,Produto 20,20.0,86.0,1.0,2025-01-15,78.0,8.0,38.51

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   data_entrada       20 non-null     datetime64[us]
 1   nro_nfe            20 non-null     str
 2   item               20 non-null     int64
 3   produto_id         20 non-null     str
 4   descricao_produto  20 non-null     str
 5   ordem_compra       20 non-null     int64
 6   qtde_recebida      20 non-null     int64
 7   filial_id          20 non-null     int64
 8   custo_unitario     20 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(4), str(3)
memory usage: 1.5 KB

None

,data_entrada,nro_nfe,item,produto_id,descricao_produto,ordem_compra,qtde_recebida,filial_id,custo_unitario
0,2025-02-27,NFE1,1,P1,Produto 1,1,77,1,84.35
1,2025-01-20,NFE2,1,P2,Produto 2,2,64,1,16.66
2,2025-02-18,NFE3,1,P3,Produto 3,3,88,1,90.36
3,2025-02-12,NFE4,1,P4,Produto 4,4,4,1,84.68
4,2025-02-19,NFE5,1,P5,Produto 5,5,95,1,98.99
5,2025-02-08,NFE6,1,P6,Produto 6,6,41,1,90.29
6,2025-01-03,NFE7,1,P7,Produto 7,7,75,1,27.22
7,2025-02-21,NFE8,1,P8,Produto 8,8,25,1,71.10
8,2025-02-13,NFE9,1,P9,Produto 9,9,57,1,19.55
9,2025-03-01,NFE10,1,P10,Produto 10,10,7,1,54.39
10,2025-01-23,NFE11,1,P11,Produto 11,11,85,1,91.89
11,2025-01-02,NFE12,1,P12,Produto 12,12,12,1,38.53
12,2025-02-20,NFE13,1,P13,Produto 13,13,7,1,60.86
13,2025-01-10,NFE14,1,P14,Produto 14,14,92,1,38.48
14,2025-01-13,NFE15,1,P15,Produto 15,15,68,1,95.58
15,2025-01-22,NFE16,1,P16,Produto 16,16,89,1,39.46
16,2025-02-24,NFE17,1,P17,Produto 17,17,10,1,10.32
17,2025-01-31,NFE18,1,P18,Produto 18,18,48,1,62.56
18,2025-02-13,NFE19,1,P19,Produto 19,19,64,1,84.54
19,2025-01-01,NFE20,1,P20,Produto 20,20,6,1,65.70

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   filial_id       20 non-null     int64
 1   idproduto       20 non-null     str
 2   descricao       20 non-null     str
 3   estoque         20 non-null     int64
 4   preco_unitario  20 non-null     float64
 5   preco_compra    20 non-null     float64
 6   preco_venda     20 non-null     float64
 7   idfornecedor    20 non-null     str
dtypes: float64(3), int64(2), str(3)
memory usage: 1.4 KB

None

,filial_id,idproduto,descricao,estoque,preco_unitario,preco_compra,preco_venda,idfornecedor
0,1,P1,Produto 1,88,42.65,144.13,40.79,F8
1,1,P2,Produto 2,28,79.52,103.56,174.18,F9
2,1,P3,Produto 3,40,119.50,24.14,60.69,F10
3,1,P4,Produto 4,73,89.67,7.75,226.50,F11
4,1,P5,Produto 5,97,135.99,36.18,89.92,F12
5,1,P6,Produto 6,38,161.31,55.37,95.60,F13
6,1,P7,Produto 7,131,153.82,14.04,46.64,F7
7,1,P8,Produto 8,71,140.57,149.50,95.28,F17
8,1,P9,Produto 9,2,30.88,137.00,164.32,F18
9,1,P10,Produto 10,38,115.71,27.77,87.70,F19
10,1,P11,Produto 11,154,147.99,29.39,44.95,F1
11,1,P12,Produto 12,78,32.47,64.63,276.58,F2
12,1,P13,Produto 13,79,194.04,58.30,99.05,F3
13,1,P14,Produto 14,9,199.56,56.80,80.74,F4
14,1,P15,Produto 15,131,101.15,107.60,29.24,F5
15,1,P16,Produto 16,177,24.64,75.94,278.88,F6
16,1,P17,Produto 17,105,195.63,126.25,183.92,F7
17,1,P18,Produto 18,198,162.20,134.12,105.61,F18
18,1,P19,Produto 19,148,184.36,121.69,234.58,F19
19,1,P20,Produto 20,196,52.04,124.87,157.93,F20

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   idfornecedor  20 non-null     str
 1   razao_social  20 non-null     str
dtypes: str(2)
memory usage: 452.0 bytes

None

   idfornecedor        razao_social
0            F1   Fornecedor 1 LTDA
1            F2   Fornecedor 2 LTDA
2            F3   Fornecedor 3 LTDA
3            F4   Fornecedor 4 LTDA
4            F5   Fornecedor 5 LTDA
5            F6   Fornecedor 6 LTDA
6            F7   Fornecedor 7 LTDA
7            F8   Fornecedor 8 LTDA
8            F9   Fornecedor 9 LTDA
9           F10  Fornecedor 10 LTDA
10          F11  Fornecedor 11 LTDA
11          F12  Fornecedor 12 LTDA
12          F13  Fornecedor 13 LTDA
13          F14  Fornecedor 14 LTDA
14          F15  Fornecedor 15 LTDA
15          F16  Fornecedor 16 LTDA
16          F17  Fornecedor 17 LTDA
17          F18  Fornecedor 18 LTDA
18          F19  Fornecedor 19 LTDA
19          F20  Fornecedor 20 LTDA

In [ ]:
# Renomear colunas desconhecidas

pedido_df = pedido_df.rename(columns={
       'Unnamed: 12':'data_pedido_2',
       'Unnamed: 13': 'item_2', 
       'Unnamed: 14':'produto_id_2', 
       'Unnamed: 15':'descricao_produto_2', 
       'Unnamed: 16':'ordem_compra_2',
       'Unnamed: 17': 'qtde_pedida_2', 
       'Unnamed: 18': 'filial_id_2', 
       'Unnamed: 19': 'data_entrega_2', 
       'Unnamed: 20': 'qtde_entregue_2',
       'Unnamed: 21': 'qtde_pendente_2', 
       'Unnamed: 22': 'preco_compra_2'
       }
    )

,pedido_id,data_pedido,item,produto_id,descricao_produto,ordem_compra,qtde_pedida,filial_id,data_entrega,qtde_entregue,...,item_2,produto_id_2,descricao_produto_2,ordem_compra_2,qtde_pedida_2,filial_id_2,data_entrega_2,qtde_entregue_2,qtde_pendente_2,preco_compra_2
0,1,2025-01-02,1,P1,Produto 1,1,96,1,2025-02-27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,2,2025-01-07,1,P2,Produto 2,2,14,1,2025-01-07,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,3,2025-01-05,1,P3,Produto 3,3,12,1,2025-01-03,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,4,2025-01-22,1,P4,Produto 4,4,27,1,2025-01-28,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,5,2025-01-28,1,P5,Produto 5,5,35,1,2025-02-28,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5,6,2025-02-22,1,P6,Produto 6,6,98,1,2025-01-05,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
6,7,2025-03-01,1,P7,Produto 7,7,34,1,2025-02-01,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
7,8,2025-02-02,1,P8,Produto 8,8,29,1,2025-02-14,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
8,9,2025-01-15,1,P9,Produto 9,9,57,1,2025-01-28,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
9,10,2025-01-09,1,P10,Produto 10,10,49,1,2025-02-09,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
10,11,2025-02-22,1,P11,Produto 11,11,24,1,2025-01-08,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
11,12,2025-02-25,1,P12,Produto 12,12,91,1,2025-02-20,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
12,13,2025-02-23,1,P13,Produto 13,13,99,1,2025-02-02,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
13,14,2025-01-21,1,P14,Produto 14,14,96,1,2025-01-01,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
14,15,2025-02-04,1,P15,Produto 15,15,45,1,2025-01-04,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
15,16,2025-02-27,1,P16,Produto 16,16,84,1,2025-01-14,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
16,17,2025-01-08,1,P17,Produto 17,17,22,1,2025-01-19,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
17,18,2025-02-17,1,P18,Produto 18,18,63,1,2025-01-02,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
18,19,2025-02-19,1,P19,Produto 19,0,20,1,2025-01-08,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
19,20,2025-02-10,1,P20,Produto 20,0,25,1,2025-01-15,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
20,21,2025-02-25,1,P12,Produto 12,0,12,1,2025-02-20,0,...,1.0,P12,Produto 12,12.0,91.0,1.0,2025-02-20,48.0,43.0,6.92
21,22,2025-02-23,1,P13,Produto 13,0,4,1,2025-02-02,0,...,1.0,P13,Produto 13,13.0,99.0,1.0,2025-02-02,91.0,8.0,65.44
22,23,2025-01-21,1,P14,Produto 14,0,6,1,2025-01-01,0,...,1.0,P14,Produto 14,14.0,96.0,1.0,2025-01-01,27.0,69.0,21.91
23,24,2025-02-04,1,P15,Produto 15,0,8,1,2025-01-04,0,...,1.0,P15,Produto 15,15.0,45.0,1.0,2025-01-04,1.0,44.0,85.04
24,25,2025-02-27,1,P16,Produto 16,0,9,1,2025-01-14,0,...,1.0,P16,Produto 16,16.0,84.0,1.0,2025-01-14,51.0,33.0,64.17
25,26,2025-01-08,1,P17,Produto 17,0,4,1,2025-01-19,0,...,1.0,P17,Produto 17,17.0,22.0,1.0,2025-01-19,7.0,15.0,74.55
26,27,2025-02-17,1,P18,Produto 18,0,3,1,2025-01-02,0,...,1.0,P18,Produto 18,18.0,63.0,1.0,2025-01-02,17.0,46.0,24.94
27,28,2025-02-19,1,P19,Produto 19,0,3,1,2025-01-08,0,...,1.0,P19,Produto 19,19.0,40.0,1.0,2025-01-08,0.0,40.0,22.21
28,29,2025-02-10,1,P20,Produto 20,0,2,1,2025-01-15,0,...,1.0,P20,Produto 20,20.0,86.0,1.0,2025-01-15,78.0,8.0,38.51

In [46]:
mapeamento = {
    'ordem_compra_2': 'ordem_compra',
    'qtde_pedida_2':'qtde_pedida',
    'qtde_entregue_2': 'qtde_entregue'
}

for origem, destino in mapeamento.items():
    
    pedido_df[destino] = pedido_df[destino].where(
        pedido_df[origem].isna(),
        pedido_df[origem]
    )

In [ ]:
# Excluir colunas desnecessarias
pedido_df_limpa = pedido_df.drop(columns=[
    'data_pedido_2',
    'item_2', 
    'produto_id_2', 
    'descricao_produto_2', 
    'ordem_compra_2',
    'qtde_pedida_2', 
    'filial_id_2', 
    'data_entrega_2', 
    'qtde_entregue_2',
    'qtde_pendente_2', 
    'preco_compra_2']
    )

,pedido_id,data_pedido,item,produto_id,descricao_produto,ordem_compra,qtde_pedida,filial_id,data_entrega,qtde_entregue,preco_compra,fornecedor_id
0,1,2025-01-02,1,P1,Produto 1,1.0,96.0,1,2025-02-27,10.0,46.67,1
1,2,2025-01-07,1,P2,Produto 2,2.0,14.0,1,2025-01-07,7.0,77.32,2
2,3,2025-01-05,1,P3,Produto 3,3.0,12.0,1,2025-01-03,2.0,47.82,3
3,4,2025-01-22,1,P4,Produto 4,4.0,27.0,1,2025-01-28,3.0,49.57,4
4,5,2025-01-28,1,P5,Produto 5,5.0,35.0,1,2025-02-28,12.0,57.18,5
5,6,2025-02-22,1,P6,Produto 6,6.0,98.0,1,2025-01-05,55.0,59.96,6
6,7,2025-03-01,1,P7,Produto 7,7.0,34.0,1,2025-02-01,29.0,49.22,7
7,8,2025-02-02,1,P8,Produto 8,8.0,29.0,1,2025-02-14,24.0,35.88,8
8,9,2025-01-15,1,P9,Produto 9,9.0,57.0,1,2025-01-28,34.0,28.48,9
9,10,2025-01-09,1,P10,Produto 10,10.0,49.0,1,2025-02-09,4.0,42.86,10
10,11,2025-02-22,1,P11,Produto 11,11.0,24.0,1,2025-01-08,12.0,14.82,11
11,12,2025-02-25,1,P12,Produto 12,12.0,91.0,1,2025-02-20,48.0,6.92,12
12,13,2025-02-23,1,P13,Produto 13,13.0,99.0,1,2025-02-02,91.0,65.44,13
13,14,2025-01-21,1,P14,Produto 14,14.0,96.0,1,2025-01-01,27.0,21.91,14
14,15,2025-02-04,1,P15,Produto 15,15.0,45.0,1,2025-01-04,1.0,85.04,15
15,16,2025-02-27,1,P16,Produto 16,16.0,84.0,1,2025-01-14,51.0,64.17,16
16,17,2025-01-08,1,P17,Produto 17,17.0,22.0,1,2025-01-19,7.0,74.55,17
17,18,2025-02-17,1,P18,Produto 18,18.0,63.0,1,2025-01-02,17.0,24.94,18
18,19,2025-02-19,1,P19,Produto 19,0.0,20.0,1,2025-01-08,0.0,22.21,19
19,20,2025-02-10,1,P20,Produto 20,0.0,25.0,1,2025-01-15,0.0,38.51,20
20,21,2025-02-25,1,P12,Produto 12,12.0,91.0,1,2025-02-20,48.0,6.92,12
21,22,2025-02-23,1,P13,Produto 13,13.0,99.0,1,2025-02-02,91.0,65.44,13
22,23,2025-01-21,1,P14,Produto 14,14.0,96.0,1,2025-01-01,27.0,21.91,14
23,24,2025-02-04,1,P15,Produto 15,15.0,45.0,1,2025-01-04,1.0,85.04,15
24,25,2025-02-27,1,P16,Produto 16,16.0,84.0,1,2025-01-14,51.0,64.17,16
25,26,2025-01-08,1,P17,Produto 17,17.0,22.0,1,2025-01-19,7.0,74.55,17
26,27,2025-02-17,1,P18,Produto 18,18.0,63.0,1,2025-01-02,17.0,24.94,18
27,28,2025-02-19,1,P19,Produto 19,19.0,40.0,1,2025-01-08,0.0,22.21,19
28,29,2025-02-10,1,P20,Produto 20,20.0,86.0,1,2025-01-15,78.0,38.51,20

In [48]:
# calcular qtde_pendente do pedido
pedido_df_limpa['qtde_pendente'] = pedido_df_limpa['qtde_pedida'] - pedido_df_limpa['qtde_entregue']